// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UI.Models;

namespace FinalProject.Migrations
{
    [DbContext(typeof(GamerDbContext))]
    [Migration("20190412224918_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("UI.Models.Gamer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("room");

                    b.Property<string>("userName");

                    b.HasKey("id");

                    b.ToTable("Gamers");
                });
#pragma warning restore 612, 618
        }
    }
}
